# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COadbms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_no', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=500)),
                ('po1', models.CharField(max_length=1)),
                ('po2', models.CharField(max_length=1)),
                ('po3', models.CharField(max_length=1)),
                ('po4', models.CharField(max_length=1)),
                ('po5', models.CharField(max_length=1)),
                ('po6', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='COatdadbms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cono', models.CharField(max_length=2)),
                ('atd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
