# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coadbms',
            name='bloomlevel',
            field=models.CharField(default='Knowledge', max_length=50),
        ),
    ]
