# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_remove_students_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
    ]
