# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_auto_20160912_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='viva',
            field=models.IntegerField(default=23),
        ),
    ]
